FROM openjdk:11
WORKDIR usr/src
ADD ./target/User-Profile-Service-0.0.1-SNAPSHOT.jar /usr/src/User-Profile-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","User-Profile-Service-0.0.1-SNAPSHOT.jar"]


